(()=>{
const KEY='pi-action-guide-v2';
const state=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const css=`
#stepActions.ag-ready{gap:12px}.ag-toolbar{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap;margin:-2px 0 12px;padding:10px 12px;border:1px solid var(--line,#1e2d3d);border-radius:10px;background:var(--panel,#0d131d)}.ag-toolbar strong{font-size:12px}.ag-toolbar small{display:block;color:var(--muted,#8a9bb0);font-size:10px;margin-top:2px}.ag-mode{display:flex;gap:6px}.ag-mode button{border:1px solid var(--line,#1e2d3d);background:var(--panel2,#111923);color:var(--muted,#8a9bb0);border-radius:8px;padding:7px 9px;font-size:10px}.ag-mode button.active{border-color:var(--purple,#8257ff);color:#fff;background:rgba(130,87,255,.16)}
#stepActions .action-item.ag-card{display:block!important;padding:0!important;overflow:hidden;border-radius:12px;background:#0a111a}#stepActions .action-item.ag-card.ag-hidden{display:none!important}.ag-action-head{display:grid;grid-template-columns:34px minmax(0,1fr) auto;gap:10px;align-items:start;padding:13px}.ag-action-num{width:30px;height:30px;border-radius:50%;background:rgba(130,87,255,.16);border:1px solid rgba(130,87,255,.35);display:grid;place-items:center;color:#c6b8ff;font-size:11px;font-weight:800}.ag-action-copy strong{display:block;font-size:12px;margin-bottom:4px}.ag-action-copy p{font-size:12px;color:#d7dfe8;line-height:1.55;margin:0}.ag-action-check{width:24px;height:24px;border-radius:50%;border:1px solid #53647b;background:#101927;color:#aab7c7;display:grid;place-items:center;font-size:11px}.ag-action-check.done{background:rgba(75,212,155,.18);border-color:#4bd49b;color:#4bd49b}
.ag-visual{border-top:1px solid var(--line,#1e2d3d);background:#05080d}.ag-visual img{display:block;width:100%;max-height:520px;object-fit:contain}.ag-placeholder{display:grid;grid-template-columns:48px 1fr;gap:12px;align-items:center;padding:16px;background:linear-gradient(145deg,#09111b,#111a28)}.ag-placeholder b{font-size:28px}.ag-placeholder strong{display:block;font-size:11px}.ag-placeholder span{display:block;color:var(--muted,#8a9bb0);font-size:10px;line-height:1.45;margin-top:3px}.ag-tools{display:flex;gap:7px;flex-wrap:wrap;padding:10px 12px;border-top:1px solid var(--line,#1e2d3d)}.ag-tools button{border:1px solid #33445d;background:#0d1724;color:#b7c5d5;border-radius:8px;padding:7px 9px;font-size:10px}.ag-detail{display:none;padding:0 12px 12px}.ag-detail.open{display:block}.ag-detail>div{border:1px solid #3b4b61;background:#0a1420;border-radius:9px;padding:10px;color:#cbd5df;font-size:10.5px;line-height:1.5}.ag-detail strong{display:block;color:#fff;margin-bottom:5px}.ag-nav{display:flex;gap:8px;margin:4px 0 18px}.ag-nav button{flex:1;min-height:42px;border:1px solid var(--line,#1e2d3d);border-radius:9px;background:var(--panel,#0d131d);color:#dbe4ee}.ag-nav button.primary{background:var(--purple,#8257ff);border-color:var(--purple,#8257ff);color:#fff}.ag-nav button:disabled{opacity:.35}.ag-modal{position:fixed;inset:0;z-index:5000;background:rgba(2,5,10,.9);display:none;align-items:center;justify-content:center;padding:18px}.ag-modal.open{display:flex}.ag-modal-box{width:min(100%,1000px);max-height:92vh;overflow:auto;background:#0b121c;border:1px solid #3a4a61;border-radius:14px;padding:12px}.ag-modal-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:9px}.ag-modal-head button{padding:7px 10px;border-radius:8px;background:#111923;color:white;border:1px solid #3a4a61}.ag-modal img{width:100%;max-height:78vh;object-fit:contain;display:block}.step-hero.ag-secondary{opacity:.6}.step-thumbnails.ag-secondary{opacity:.6}
@media(max-width:700px){.ag-toolbar{display:grid}.ag-mode{display:grid;grid-template-columns:1fr 1fr}.ag-mode button{min-height:42px}.ag-action-copy p{font-size:13px}.ag-tools{display:grid;grid-template-columns:1fr 1fr}.ag-tools button{min-height:42px}.ag-nav{position:sticky;bottom:62px;z-index:20;background:rgba(7,11,18,.94);padding:8px;border:1px solid var(--line,#1e2d3d);border-radius:11px}.ag-nav button{min-height:48px}}
`;
if(!document.getElementById('ag-style')){const s=document.createElement('style');s.id='ag-style';s.textContent=css;document.head.appendChild(s)}
function getContext(){const links=[...document.querySelectorAll('.step-title-area .breadcrumb .text-link')];return{project:(links.at(-1)?.textContent||'Project').trim(),step:(document.querySelector('.step-title-area h1')?.textContent||'Step').trim()}}
function imageFor(project,step,action){const t=(project+' '+step+' '+action).toLowerCase();if(/dsi|ribbon|display cable|touchscreen connector/.test(t))return '/assets/dsi-ribbon-reference.jpg';if(/smart mirror|two-way mirror|shadow box|blackout|mirror sheet/.test(t))return '/assets/smart-mirror-finished-reference.jpg';if(/port|usb-c|micro-hdmi|ethernet|gpio17|gpio header|microsd/.test(t))return '/assets/pi5-port-map-reference.jpg';return ''}
function iconFor(t){t=t.toLowerCase();if(/ssh|terminal|command|python|chromium|node|npm|git/.test(t))return '⌨️';if(/mirror/.test(t))return '🪞';if(/gpio|breadboard|led|resistor|button/.test(t))return '💡';if(/display|screen|dsi/.test(t))return '🖥️';if(/power|usb-c/.test(t))return '🔌';if(/keyboard|cyberdeck/.test(t))return '⌨️';return '🧰'}
function helpFor(a){a=a.toLowerCase();if(/dsi|ribbon|display/.test(a))return 'Power the Pi completely off. Check that the latch is open before inserting the ribbon, the ribbon is square and fully seated, and the latch closes without force. Recheck both ends.';if(/gpio|breadboard|led|resistor|button/.test(a))return 'Power off before rewiring. Verify the physical GPIO pin, breadboard row, resistor path, LED polarity, and GND. Compare one connection at a time.';if(/ssh/.test(a))return 'Confirm both devices are on the same network. Try the Pi IP address instead of nikkipi.local. Recheck your username and that SSH was enabled in Raspberry Pi Imager.';if(/mirror/.test(a))return 'Test the display by itself first. Then add the mirror. If the result is too dim, check mirror orientation, brightness, room lighting, and blackout masking.';return 'Undo only the last action, compare your screen or hardware to the reference, then repeat this action before moving on.'}
function modal(src,title){let m=document.querySelector('.ag-modal');if(!m){m=document.createElement('div');m.className='ag-modal';m.innerHTML='<div class="ag-modal-box"><div class="ag-modal-head"><strong></strong><button>Close</button></div><img></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}m.querySelector('strong').textContent=title;m.querySelector('img').src=src;m.classList.add('open')}
function enhance(){const list=document.querySelector('#stepActions');if(!list||!list.children.length||list.dataset.agReady==='1')return;const raw=[...list.querySelectorAll('.action-item')];if(!raw.length)return;const {project,step}=getContext();const base=`${project}::${step}`;let mode=state[`mode::${project}`]||'guided';let active=Math.max(0,Math.min(Number(state[`active::${base}`]||0),raw.length-1));
const title=document.querySelector('.step-actions-section-title');const toolbar=document.createElement('div');toolbar.className='ag-toolbar';toolbar.innerHTML=`<div><strong>Do it with me</strong><small data-ag-status></small></div><div class="ag-mode"><button data-ag-mode="guided">Guided Mode</button><button data-ag-mode="full">Full Step</button></div>`;(title||list).before(toolbar);
raw.forEach((el,i)=>{const text=(el.querySelector('span')?.textContent||el.textContent).trim();const src=imageFor(project,step,text);const existingCheck=el.querySelector('.action-check');const done=existingCheck?.textContent.trim()==='✓'||!!state[`done::${base}::${i}`];const visual=src?`<div class="ag-visual"><img src="${src}" alt="Visual reference for ${esc(text)}" loading="lazy"></div>`:`<div class="ag-placeholder"><b>${iconFor(text)}</b><div><strong>Focus on this action only</strong><span>Do this one thing, then compare the physical result or screen before continuing.</span></div></div>`;el.classList.add('ag-card');el.dataset.agIndex=i;el.innerHTML=`<div class="ag-action-head"><span class="ag-action-num">${i+1}</span><div class="ag-action-copy"><strong>Action ${i+1}</strong><p>${esc(text)}</p></div><button class="ag-action-check ${done?'done':''}" data-ag-check>${done?'✓':'○'}</button></div>${visual}<div class="ag-tools">${src?'<button data-ag-show>🔎 Show me where</button><button data-ag-compare>✓ Correct vs wrong</button>':''}<button data-ag-help>✦ Mine doesn’t look like this</button><button data-ag-note>📝 Note</button></div><div class="ag-detail"><div></div></div>`;el.querySelector('[data-ag-check]').onclick=()=>{state[`done::${base}::${i}`]=!state[`done::${base}::${i}`];if(state[`done::${base}::${i}`]&&mode==='guided'&&i<raw.length-1){active=i+1;state[`active::${base}`]=active}save();render()};if(src)el.querySelector('[data-ag-show]').onclick=()=>modal(src,`Action ${i+1}: ${text}`);const cmp=el.querySelector('[data-ag-compare]');if(cmp)cmp.onclick=()=>{const d=el.querySelector('.ag-detail'),b=d.firstElementChild;b.innerHTML='<strong>Correct vs wrong</strong>Correct means the component is aligned, fully seated, not under strain, and matches the visual. Wrong includes reversed orientation, partial insertion, pinched cables, forced latches, or mismatched pins.';d.classList.toggle('open')};el.querySelector('[data-ag-help]').onclick=()=>{const d=el.querySelector('.ag-detail'),b=d.firstElementChild;b.innerHTML=`<strong>Troubleshoot this action</strong>${esc(helpFor(text))}`;d.classList.toggle('open')};el.querySelector('[data-ag-note]').onclick=()=>{const k=`note::${base}::${i}`;const v=prompt('Note for this action:',state[k]||'');if(v!==null){state[k]=v;save()}}});
const nav=document.createElement('div');nav.className='ag-nav';nav.innerHTML='<button data-ag-prev>← Previous action</button><button class="primary" data-ag-next>Next action →</button>';list.after(nav);const hero=document.querySelector('.step-hero');if(hero)hero.classList.add('ag-secondary');const thumbs=document.querySelector('.step-thumbnails');if(thumbs)thumbs.classList.add('ag-secondary');
function render(){const done=raw.filter((_,i)=>state[`done::${base}::${i}`]).length;toolbar.querySelector('[data-ag-status]').textContent=`${done}/${raw.length} actions checked · action ${active+1} of ${raw.length}`;toolbar.querySelectorAll('[data-ag-mode]').forEach(b=>b.classList.toggle('active',b.dataset.agMode===mode));raw.forEach((x,i)=>x.classList.toggle('ag-hidden',mode==='guided'&&i!==active));nav.style.display=mode==='guided'?'flex':'none';nav.querySelector('[data-ag-prev]').disabled=active===0;nav.querySelector('[data-ag-next]').disabled=active===raw.length-1;raw.forEach((x,i)=>{const b=x.querySelector('[data-ag-check]');const d=!!state[`done::${base}::${i}`];b.classList.toggle('done',d);b.textContent=d?'✓':'○'})}
toolbar.querySelectorAll('[data-ag-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.agMode;state[`mode::${project}`]=mode;save();const toggle=document.querySelector('#guidedCheck');if(toggle)toggle.checked=mode==='guided';render()});nav.querySelector('[data-ag-prev]').onclick=()=>{active=Math.max(0,active-1);state[`active::${base}`]=active;save();render();list.scrollIntoView({behavior:'smooth',block:'start'})};nav.querySelector('[data-ag-next]').onclick=()=>{active=Math.min(raw.length-1,active+1);state[`active::${base}`]=active;save();render();list.scrollIntoView({behavior:'smooth',block:'start'})};const toggle=document.querySelector('#guidedCheck');if(toggle){toggle.checked=mode==='guided';toggle.onchange=()=>{mode=toggle.checked?'guided':'full';state[`mode::${project}`]=mode;save();render()}}list.dataset.agReady='1';list.classList.add('ag-ready');render()}
const obs=new MutationObserver(()=>{const l=document.querySelector('#stepActions');if(l&&l.children.length&&l.dataset.agReady!=='1')setTimeout(enhance,40)});obs.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',()=>setTimeout(enhance,250));setTimeout(enhance,700);
})();