(()=>{
const A=(title,detail)=>({title,detail});
const T=(problem,fix)=>({problem,fix});
const C=(label,code,result)=>({label,code,result});
const V=(scene,caption,photo=null,photos=null)=>({scene,caption,photo,photos});
const S=(title,why,time,visual,actions,success,warning='',trouble=[],commands=[])=>({title,why,time,visual,actions,success,warning,trouble,commands});
const required=(name,why)=>({name,why,required:true});
const optional=(name,why)=>({name,why,required:false});
const basePrep=(p)=>S('Lay out, identify, and inspect every part',`Before building ${p.title}, make sure every part is present, undamaged, and understood. This prevents forcing the wrong connector or discovering a missing item halfway through assembly.`,'15–25 min',V(p.scene,`Inventory layout for ${p.title}. Match each item in the guide to the physical part on your table.`),[
A('Clear a safe work area','Use a dry, uncluttered table with enough room for the Pi, display, cables, tools, and project enclosure. Put a soft towel under the display so the glass cannot scratch.'),
A('Match every material to the list','Place each required item in a row. Read the printed labels on power supplies, cables, batteries, and boards. Do not assume two similar-looking cables are interchangeable.'),
A('Inspect connectors before inserting anything','Look for bent pins, cracked connector latches, damaged ribbon ends, torn insulation, or loose USB-C plugs. Stop and replace any damaged part.'),
A('Separate powered and unpowered work','Keep the USB-C power lead physically away from the Pi until a step explicitly tells you to power on. Hardware assembly and GPIO wiring should begin with power disconnected.'),
A('Photograph the starting layout','Take one phone photo of the parts and another close-up of cable labels. These photos give you a reference if you later forget which cable or orientation you used.'),
A('Open this guide on a second device if possible','A phone or laptop beside the work area lets you keep the Pi powered off while reading connector instructions and comparing the visual reference.')
],[`Every required part is accounted for or intentionally marked optional.`,`No connector, cable, display, or board shows obvious damage.`,`The Pi is still powered off when you finish this phase.`],'Never force a connector. If a cable needs unusual pressure, stop and confirm that it is the correct cable and orientation.',[T('A part does not match the picture','Check the exact model number printed on the part. Use the material description rather than color alone, because vendors change cable and board colors.'),T('You are missing a required part','Do not improvise with a higher-voltage supply, unknown ribbon cable, or random resistor value. Mark the project paused until the correct part is available.')]);
const osPrep=(p)=>S('Prepare Raspberry Pi OS and prove the Pi is healthy',`Build on a known-good Raspberry Pi installation before adding ${p.title}-specific hardware or software.`,'30–60 min',V('pi-os','Raspberry Pi Imager, first boot, Wi-Fi, SSH, and system update are verified before project-specific work.','/assets/setup/imager-ssh-generated.jpg',[
{label:'Imager settings',src:'/assets/setup/imager-ssh-generated.jpg',caption:'Preconfigure username, password, Wi-Fi, hostname, locale, and SSH before writing the card.'},
{label:'First boot',src:'/assets/boot-screen.jpg',caption:'The Pi should reach Raspberry Pi OS successfully before project-specific assembly.'}
]),[
A('Write Raspberry Pi OS 64-bit Desktop','Insert the microSD card into your computer, open Raspberry Pi Imager, choose Raspberry Pi 5, choose Raspberry Pi OS 64-bit Desktop, and select only the intended microSD card.'),
A('Preconfigure access before writing','In Imager customization, set a username and password, Wi-Fi credentials, hostname, locale, and enable SSH with password authentication. Save the settings, then write and verify the card.'),
A('Insert the card with the Pi powered off','After Imager finishes verification, eject the microSD cleanly. Insert it into the Pi until fully seated. Do not insert or remove the card while the Pi is powered.'),
A('Complete first boot','Connect the display or temporary HDMI monitor, keyboard if needed, then connect USB-C power last. Finish any Raspberry Pi OS prompts and confirm the desktop is usable.'),
A('Update the operating system','Open Terminal and run the update and full-upgrade commands below. Let them finish before rebooting.'),
A('Verify network and temperature','Confirm Wi-Fi works, SSH works from another device if you enabled it, and the Pi reports a temperature without errors.'),
A('Reboot once before continuing','A clean reboot confirms the updated OS, microSD, power supply, and display can all restart normally.')
],[`Raspberry Pi OS reaches the desktop after a reboot.`,`Wi-Fi is connected and web pages load.`,`The update command finishes without unresolved package errors.`,`The Pi remains stable with no undervoltage warning.`],'If you see an undervoltage warning, random reboot, or corrupted microSD message, solve that before building the project.',[T('The Pi does not appear on Wi-Fi','Check that the SSID and password entered in Imager match the network exactly. Temporarily connect a monitor and inspect the network menu.'),T('SSH says connection refused','Confirm SSH was enabled in Imager or enable it from Raspberry Pi Configuration, then retry using the Pi hostname or IP address.'),T('The screen is blank','Power off first, reseat the display/HDMI connection, then test again. Do not repeatedly reconnect a DSI ribbon while powered.')],[C('Update Raspberry Pi OS','sudo apt update && sudo apt full-upgrade -y','Package lists update and installed packages complete successfully.'),C('Check temperature','vcgencmd measure_temp','A temperature line such as temp=45.0\'C appears.')]);
const finalTest=(p)=>S('Run a complete final validation before calling it finished',`Test ${p.title} exactly the way you plan to use it. A project is not complete just because it worked once on the workbench.`,'30–60 min',V(p.scene,`Finished ${p.title} validation: power, display, controls, network, heat, and restart behavior are checked together.`),[
A('Start from fully powered off','Shut Raspberry Pi OS down cleanly, disconnect power for 10 seconds, then reconnect power. Do not begin this test from an already-running state.'),
A('Watch the entire cold boot','Confirm the Pi starts without manual cable movement, recovery prompts, or repeated restarts. Note how long it takes to reach the project screen.'),
A('Test every control once','Tap, click, press, or trigger every user-facing control. Include Back, Home, Settings, Exit, or maintenance controls that are easy to forget.'),
A('Test the failure path','Briefly disconnect Wi-Fi or close a data source if practical. Confirm the UI shows a useful error instead of freezing or becoming blank.'),
A('Run continuously','Leave the project running for at least 30 minutes in its final physical position. Watch for flicker, thermal warnings, lag, dropped Wi-Fi, or cable movement.'),
A('Check temperature and physical clearance','Read the Pi temperature. Feel only the outside of the case carefully. Confirm vents remain open and no cable is being pulled, pinched, or sharply folded.'),
A('Reboot one more time','After the continuous test, reboot and verify the project returns to its normal screen without repair steps.')
],[`A cold boot reaches the intended project screen.`,`Every primary control works.`,`No cable or component moves during normal handling.`,`The project runs for at least 30 minutes without instability.`,`A second reboot succeeds.`],'Do not permanently seal an enclosure or mount the project where it is hard to reach until this phase passes.',[T('It works only after touching a cable','Power off and reseat or replace that cable. Intermittent connections become worse after mounting.'),T('It becomes unstable after 20–30 minutes','Check temperature, airflow, power warnings, and background processes. Solve heat or power instability before leaving it unattended.'),T('Kiosk or app does not return after reboot','Test the launch command manually first, then correct the autostart configuration instead of adding duplicate launch entries.')],[C('Check temperature','vcgencmd measure_temp','Temperature is displayed and the Pi remains stable.')]);
const maintain=(p)=>S('Document the build and set a maintenance routine',`${p.title} should remain understandable months from now, even after you forget the exact cable path or configuration.`,'15–20 min',V('maintenance',`Save a finished photo, software notes, and a short maintenance checklist for ${p.title}.`),[
A('Take finished photos','Photograph the front, back, cable routing, and any hidden connectors before the final back panel or mounting position makes them hard to see.'),
A('Save the software location','Write down the production URL, local folder or repository name, and any environment-variable names. Do not write secret values in the guide.'),
A('Record custom settings','Note brightness, orientation, chosen GPIO pins, timers, collection names, or other values you changed from defaults.'),
A('Plan safe updates','Update Raspberry Pi OS periodically, but avoid doing major upgrades immediately before an event or time when you need the project to work.'),
A('Inspect physical parts','Every few months, check adhesive, Velcro, cable strain, ventilation, and dust. Reattach loose parts before they fall against the display or Pi.'),
A('Keep a known-good recovery path','Keep the microSD image or configuration backed up so you can restore the Pi without rebuilding every setting from memory.')
],[`You have photos of hidden assembly details.`,`The project settings and recovery information are documented.`,`No password, token, or API key was written into a public file.`],'Never include private credentials in screenshots, public GitHub files, or browser-visible JavaScript.',[T('An update breaks the project','Use your notes to identify the last known-good configuration. Revert one change at a time rather than changing several settings together.')]);
const wrap=(p)=>({...p,phases:[basePrep(p),osPrep(p),...p.phases,finalTest(p),maintain(p)]});
const projects=[];
projects.push(wrap({id:'smart-mirror',title:'Smart Mirror',icon:'🪞',difficulty:'Medium',time:'7–10 hours',category:'Display',scene:'mirror',summary:'Build a two-way smart mirror in the 12 × 12 shadow box with the Pi 5 and 7-inch DSI display.',goal:'A stable mirror that cold-boots into a black-background dashboard, hides hardware behind the reflective layer, and can run safely in its frame.',materials:[required('Raspberry Pi 5 4GB','Runs the mirror dashboard and kiosk browser.'),required('iUniker Pi 5 metal case','Protects and cools the Pi.'),required('7-inch DSI touchscreen','Displays the mirror interface.'),required('Pi 5-compatible DSI FPC cable','Connects the touchscreen to the Pi.'),required('12 × 12 shadow box','Holds the mirror, display, Pi, and blackout layers.'),required('Two-way acrylic mirror sheet','Reflects the room while transmitting display light.'),required('45W USB-C power supply','Provides stable Pi 5 power.'),required('128 GB microSD','Stores Raspberry Pi OS.'),required('Heavy-duty Velcro','Creates removable mounts.'),required('Black foam board or matte black tape','Blocks internal reflections and visible hardware.'),optional('Painter tape','Marks center lines during dry-fit.'),required('Precision screwdriver set','Opens and secures hardware.')],safety:['Always power the Pi completely off before touching the DSI ribbon.','Do not press mounting hardware into the LCD surface.','Keep Pi 5 case vents open.','Do not cut mirror acrylic until the optical test passes.'],phases:[
S('Prove the mirror effect before cutting or mounting','Your exact mirror acrylic, room lighting, and display brightness determine whether the illusion works.','20–30 min',V('mirror-test','Hold the two-way mirror sheet directly in front of a bright white-on-black test screen.','/assets/smart-mirror-finished-reference.jpg'),[
A('Place the display on a soft towel','Keep the LCD face up, supported by its rigid frame, and free of screws or tools underneath.'),A('Connect and boot while everything is loose','Use the normal DSI/display connection and Pi power, but do not place anything in the frame yet.'),A('Open a black test screen','Show a large white clock, one line of white text, and one bright icon on a pure black background.'),A('Hold the mirror sheet in front','Keep any protective film on if it is transparent enough for testing. Hold the mirror parallel to the LCD, as close as practical without scratching it.'),A('Test two lighting conditions','Check once with normal room lights and once with the room dim. Look straight on and from your normal standing angle.'),A('Adjust brightness','Increase display brightness only until the white content is clearly readable. Stop if the mirror reflection becomes washed out.'),A('Mark the usable display area','Use painter tape on the protective layer or frame edge to note where the visible screen should sit behind the mirror.')],[`White text is readable through the mirror.`,`Black screen areas mostly disappear into the reflection.`,`The effect is acceptable in the room where the mirror will live.`],'Do not cut acrylic or add permanent adhesive until this phase passes.',[T('The screen is too dim behind the mirror','Increase brightness, reduce room light, verify the reflective side/orientation recommended by the mirror supplier, and reduce unnecessary layers between mirror and LCD.'),T('You can see the Pi or frame through black areas','That is handled in the blackout phase. First confirm the display itself is bright enough.')]),
S('Dry-fit the full frame stack','Confirm every physical layer fits before adhesive or final cable routing.','30–45 min',V('mirror-stack','Front-to-back stack: shadow-box front, two-way mirror, black mask, display, Pi case, cable space, back panel.','/assets/pi5-port-map-reference.jpg'),[
A('Remove the shadow-box back','Set aside the rear panel and any decorative insert. Keep screws together in a cup.'),A('Place the mirror at the front','Seat it where the original glass or front insert belongs. Do not bend the acrylic.'),A('Center the display behind it','Keep the LCD face parallel to the mirror. View from the front and move it until the active screen is centered.'),A('Place the Pi case behind or beside the display','Choose a position that leaves USB-C power, DSI connection, and case ventilation accessible.'),A('Plan the cable exit','Decide where the USB-C power lead exits the frame. Avoid routing it across a sharp edge or underneath a mounting point.'),A('Hold the back panel in place','Do not fasten it yet. Check that nothing presses into the LCD, connector, or Pi case.'),A('Mark positions with painter tape','Mark display edges, Pi case location, and cable path so the layout can be reproduced after you remove parts.')],[`The rear panel can sit in its normal position without squeezing components.`,`The display is centered from the front.`,`Power and DSI cable paths have clearance.`],'Pressure on an LCD can cause bright spots, touch errors, or breakage. The back panel must not clamp the display.'),
S('Mount the display and black out the cavity','Secure the screen reversibly and make the interior disappear behind black pixels.','45–60 min',V('mirror-mount','The display is held by its rigid edges; matte-black material surrounds only the inactive area.'),[
A('Power down and unplug USB-C','Wait until activity lights stop before handling the display or Pi.'),A('Clean rigid mounting surfaces','Wipe only frame or backing surfaces where Velcro will attach. Keep cleaner away from exposed electronics.'),A('Apply short Velcro strips','Attach to the display frame or a rigid backing plate, never across the active LCD, flex cable, or connector.'),A('Mount using your center marks','Press only on rigid frame edges. Return to the front and correct tilt before continuing.'),A('Inspect through the mirror with display off','Look for shiny Pi surfaces, white cable, wood, or gaps that are visible.'),A('Cut a black mask','Use black foam board or matte tape around the active display area. Do not cover visible pixels.'),A('Keep cooling surfaces exposed','Leave the metal Pi case, fins, and ventilation path open. Do not wrap the Pi in foam.'),A('Power on and recheck','Use a black screen and confirm only intentional content is obvious through the mirror.')],[`The display is level and does not move when the frame is gently tilted.`,`Black screen areas look like a normal dark mirror.`,`Pi ventilation remains open.`],'Never use adhesive where it can pull on the DSI connector or touchscreen flex cable.'),
S('Connect and route the DSI ribbon correctly','A DSI ribbon can work intermittently if it is reversed, crooked, only partly inserted, or sharply creased.','20–30 min',V('dsi','Gold contacts and blue stiffener orientation are matched to the connector; ribbon is fully seated and curves gently.',null,[{label:'Align ribbon',src:'/assets/smart-mirror/dsi-align.jpg',caption:'Match the contact/stiffener orientation before insertion.'},{label:'Fully seated',src:'/assets/smart-mirror/dsi-seated.jpg',caption:'The ribbon is inserted evenly to the reference line and the latch is closed.'}]),[
A('Shut the Pi down completely','Disconnect USB-C power. The display should be dark and the Pi should have no power before touching DSI.'),A('Open the connector latch gently','Use a fingernail or plastic tool. Move both ends of the latch evenly; do not pry it off.'),A('Match ribbon orientation','Compare the gold contacts and blue stiffener to the reference image before inserting.'),A('Insert the ribbon straight','Slide it evenly until the printed line or stiffener reaches the connector body. Both sides should be equally deep.'),A('Close the latch evenly','Press the latch ends down without pulling the cable back out.'),A('Route a broad curve','Use at least roughly a finger-width bend radius. Never fold the ribbon sharply like paper.'),A('Add light strain relief','Secure the ribbon path with a loose clip or small tape tab away from hot surfaces. Do not clamp the ribbon.'),A('Hold the rear panel in place again','Confirm closing the frame does not crease, pinch, or tug the ribbon.')],[`The DSI cable is straight in both connectors.`,`No sharp fold is visible.`,`The back panel can close without touching the ribbon.`],'Never connect or disconnect DSI while the Pi is powered.',[T('Display flickers when the frame moves','Power off and reseat both ends. If the ribbon has a visible crease, replace it.'),T('Display stays black after reconnection','Power off, verify connector orientation and latch position on both ends, then retest before changing software.')]),
S('Configure a real mirror kiosk screen','Make the Pi boot into a sparse, black-background interface instead of a normal desktop.','45–75 min',V('mirror-ui','Pure black background, large white clock, compact weather/calendar blocks, no visible browser chrome.'),[
A('Open the production mirror URL in Chromium','Test the normal page first before using kiosk flags.'),A('Use pure black for unused areas','The mirror illusion depends on black pixels. Avoid gray cards covering the whole screen.'),A('Keep content sparse','Use a large clock and only a few high-value widgets. Readability through reflective acrylic matters more than information density.'),A('Test kiosk mode manually','Close other Chromium windows, then run the kiosk command below using your actual production URL.'),A('Confirm touch and escape path','Verify touch works and you know how to exit kiosk mode for maintenance before enabling autostart.'),A('Add autostart only after manual success','Use the Raspberry Pi desktop autostart method appropriate to your current OS. Add exactly one kiosk launch entry.'),A('Reboot twice','Cold boot twice and confirm Chromium reaches the mirror URL without keyboard input.')],[`A cold boot reaches the mirror page automatically.`,`No browser address bar is visible in normal use.`,`The page remains readable through the mirror.`],'Do not put API keys or other secrets into browser-visible JavaScript or URL query strings.',[T('Chromium opens but not full-screen','Test the exact kiosk command in Terminal and close existing Chromium processes before debugging autostart.'),T('Two browser windows open after login','You probably have duplicate autostart entries. Keep one launch method only.')],[C('Manual kiosk test','chromium --kiosk https://pi-command-center.vercel.app','Chromium opens full-screen on the mirror page.')]),
S('Close the frame and repeat the heat test','Final assembly changes airflow, so test again with the actual back panel installed.','45–60 min',V('mirror-finish','Rear panel closed without cable pressure; power exits cleanly; mirror remains aligned.'),[
A('Run 30 minutes with the back still open','Watch display stability and read temperature at least twice.'),A('Power off before closing the back','Arrange DSI and USB-C exactly along the tested paths.'),A('Close the panel slowly','Stop immediately if you feel spring pressure. Reopen and move the obstruction instead of forcing it.'),A('Secure the panel','Use the original retainers/screws without overtightening into acrylic or electronics.'),A('Power on and inspect the front','Confirm the display did not shift and no new bright gaps appear through the mirror.'),A('Run another 20–30 minutes closed','Check temperature, Wi-Fi, touch, and display stability in the final enclosure.'),A('Choose wall or desk placement','Make sure the USB-C cable is supported and the frame cannot fall or trap heat against a wall.')],[`Closed-frame temperature remains stable.`,`No display flicker or touch failure occurs.`,`The display remains centered after the back is installed.`],'If the closed frame gets much hotter than the open test, add airflow or reposition the Pi before leaving it on for long periods.')
]}));
projects.push(wrap({id:'dashboard',title:'Personal Dashboard',icon:'🖥️',difficulty:'Easy',time:'4–6 hours',category:'Software',scene:'dashboard',summary:'Create the touch-first command center that becomes the software foundation for several other builds.',goal:'A responsive 800 × 480 dashboard with reliable touch navigation, reusable widgets, display modes, and a clean kiosk experience on the real Pi.',materials:[required('Raspberry Pi 5','Runs the dashboard in Chromium.'),required('7-inch touchscreen','Primary touch interface.'),required('Raspberry Pi OS','Provides the kiosk environment.'),required('Chromium','Runs the web dashboard.'),required('Vercel-hosted dashboard','Provides the production app URL.'),optional('Mini keyboard','Useful during setup and troubleshooting.')],safety:['Do not expose private API keys in browser JavaScript.','Keep a visible or known method to exit kiosk mode.'],phases:[
S('Design around the real 800 × 480 screen','The Pi display should drive the design instead of being treated as a shrunken desktop.','30–45 min',V('dashboard-wireframe','800 × 480 layout with a compact header, two-column card grid, and large touch targets.'),[
A('Set a browser test viewport to 800 × 480','Use developer tools on your normal computer so you can catch clipping before moving to the Pi.'),A('Choose 44–48 px minimum touch targets','Buttons and chips need enough height and spacing for a finger.'),A('Define six primary destinations','Use Today, Fitness, Focus, Photos, Devices, and Settings or a similarly small set.'),A('Keep critical content above the fold','Time, next event, focus state, and status should appear before any long scroll.'),A('Remove hover-only behavior','Every action must have a tap/click state. A touchscreen has no reliable mouse hover.'),A('Test with simulated long text','Use long event names and status messages to ensure cards wrap instead of overflowing.')],[`No horizontal scrollbar appears at 800 × 480.`,`Primary buttons can be tapped without precision.`,`Long text wraps without cutting off controls.`]),
S('Build the shell and navigation first','Stable navigation prevents every later widget from inventing its own layout.','45–60 min',V('dashboard-shell','Header + content region + persistent navigation with consistent card spacing.'),[
A('Create one compact header','Show time/date, connection state, and Settings. Avoid a tall desktop-style masthead.'),A('Create the content grid','Use two columns at Pi width and collapse to one column on narrow phones.'),A('Add persistent navigation','Place it where it never covers cards or buttons.'),A('Create shared card styles','Use the same padding, type scale, title placement, loading state, and error state across widgets.'),A('Add active navigation state','The current destination should be visually obvious.'),A('Test every destination with placeholder cards','Navigation should be finished before connecting live data.')],[`Switching sections does not cause layout jumps.`,`Every destination has a clear active state.`,`Navigation never covers interactive content.`]),
S('Build reusable widgets with loading and error states','One failed data source should not break the whole dashboard.','60–90 min',V('dashboard-widgets','Clock, weather, calendar, focus, and Pi-status cards each render independently.'),[
A('Start with a local clock widget','It should render without any network dependency.'),A('Add a weather card','Show current condition and a short forecast only. Include Loading and Unable to load states.'),A('Add a calendar summary','Show the next few events rather than a full month grid on the home screen.'),A('Add focus status','Show current task, timer state, and a clear route into the Pomodoro project.'),A('Add Pi status','Begin with online/offline and later add temperature through a local Pi endpoint.'),A('Keep each widget isolated','A caught fetch error should stay inside that card instead of throwing across the whole page.')],[`Each widget can fail independently.`,`The home screen remains usable if weather or calendar data is unavailable.`,`Loading states do not shift the entire layout.`]),
S('Add Dashboard, Mirror, Focus, Photos, and Glance modes','One app can support several physical projects if the modes are intentionally different.','45–60 min',V('dashboard-modes','Mode selector changes the same app into sparse Mirror, focused timer, photo, and passive Glance layouts.'),[
A('Create a mode selector in Settings','Do not clutter the normal home view with mode configuration.'),A('Persist the selected mode','Save it locally so refreshes do not unexpectedly return to the default.'),A('Make Mirror mode black and sparse','Use black unused space and bright high-contrast text.'),A('Make Focus mode distraction-free','Hide unrelated widgets while a focus session is running.'),A('Make Photos mode image-first','The photo should dominate the display, not navigation chrome.'),A('Make Glance mode passive','Use large readable summaries and automatic rotation.'),A('Always provide a route back','Each mode needs a reliable Home or Exit path for maintenance.')],[`Mode changes happen without a broken intermediate state.`,`The selected mode survives refresh.`,`You cannot trap yourself in a mode.`]),
S('Test touch, scrolling, and kiosk behavior on the physical Pi','Desktop simulation cannot reproduce finger targeting, real screen distance, or the Pi browser exactly.','45–60 min',V('dashboard-pi','The production URL is tested on the actual 7-inch Pi screen with a finger.'),[
A('Deploy the current version','Use the production or preview URL you intend to run on the Pi.'),A('Open it in Pi Chromium','Use the exact physical display and normal orientation.'),A('Tap every control with a finger','Do not use the mouse for this test. Note any small or closely packed targets.'),A('Check all scroll boundaries','Open long Settings, calendar, and error content. Nothing should be unreachable behind fixed navigation.'),A('Rotate through every display mode','Watch for clipped text, unexpected keyboards, or full-screen elements that exceed 800 × 480.'),A('Test manual kiosk mode','Confirm the production URL behaves correctly before enabling autostart.'),A('Fix usability before adding features','A smaller reliable dashboard is better than a dense one that is hard to tap.')],[`Every primary action works by touch.`,`No page has horizontal overflow.`,`Kiosk mode shows the intended page without browser chrome.`],[ ],[T('A card is cut off on the Pi but not desktop','Test the actual browser viewport dimensions and safe areas. Avoid fixed pixel heights on long content.'),T('Taps open the wrong control','Increase target size and spacing. Do not rely on tiny icons.')],[C('Manual kiosk test','chromium --kiosk https://pi-command-center.vercel.app','The dashboard opens full-screen.')])
]}));
projects.push(wrap({id:'ai-terminal',title:'Mini AI Terminal',icon:'💬',difficulty:'Medium',time:'5–7 hours',category:'Software',scene:'terminal',summary:'Turn the Pi into a dedicated AI terminal controlled from the touchscreen and mini keyboard.',goal:'A touch-friendly full-screen AI client with secure server-side credentials, project-aware shortcuts, and no unrestricted remote shell access.',materials:[required('Raspberry Pi 5','Runs the terminal interface.'),required('7-inch touchscreen','Primary display.'),required('Rii mini wireless keyboard','Compact text input.'),required('Chromium','Runs the web client.'),required('Vercel server route','Keeps AI credentials server-side.'),required('AI API credential','Stored only as a server environment variable.')],safety:['Never place an AI API key in public HTML or client JavaScript.','Do not give a remote AI service unrestricted shell access to the Pi.'],phases:[
S('Pair and fully test the mini keyboard','Input hardware problems can look exactly like web-app bugs.','20–30 min',V('keyboard','Mini keyboard, receiver/Bluetooth connection, touchpad, and full key test.'),[
A('Charge or install fresh batteries','Start with a known-good power state.'),A('Connect the receiver or pair Bluetooth','Use the keyboard manual for the correct connection type.'),A('Open a plain text editor','Test outside your web app first.'),A('Type every letter row and number row','Include O, I, J, K, L, M, U and other keys that can be affected by accessibility/mouse-key settings.'),A('Test Backspace, Enter, Shift, arrows, and modifiers','Confirm navigation keys do not unexpectedly move a mouse pointer.'),A('Test the touchpad and clicks','Use the real distance and seating position planned for the terminal.'),A('Reboot and retest','Make sure the keyboard reconnects without a special repair step.')],[`Every required key enters the expected character.`,`Touchpad and click work.`,`The keyboard reconnects after reboot.`],'Solve keyboard/accessibility settings before changing the AI app.'),
S('Build the large, simple chat interface','The 7-inch display needs a different chat layout than a desktop browser.','45–75 min',V('terminal-ui','Large multiline prompt, scrollable response region, Send/Stop/Clear/New Chat buttons, and quick-action chips.'),[
A('Create one large prompt box','It should be easy to tap and large enough for several lines.'),A('Keep Send, Stop, Clear, and New Chat visible','Do not hide basic controls behind tiny menus.'),A('Keep the response region independently scrollable','The input should remain reachable after a long answer.'),A('Support Shift+Enter for a new line','Only submit with Enter if that behavior is explicit and comfortable on the mini keyboard.'),A('Add clear streaming/loading feedback','Disable duplicate sends while a request is already running.'),A('Add quick prompts','Examples: Explain this build step, Troubleshoot this step, Open Dashboard, Device Status.'),A('Test entirely by touch and mini keyboard','No desktop-only hover control should be required.')],[`You can send, stop, scroll, clear, and begin a new chat without precision tapping.`,`Long answers do not push the prompt off-screen permanently.`]),
S('Move AI requests behind a server route','The browser must never receive the raw provider secret.','45–60 min',V('terminal-secure','Browser sends prompt to Vercel server route; server reads secret environment variable and calls provider.'),[
A('Create a server endpoint','Accept only the fields needed for the chat request.'),A('Store the provider key in Vercel Environment Variables','Use the provider variable name required by your server code. Do not commit the value.'),A('Send the user prompt to your endpoint','The browser should call your own server route rather than the provider directly.'),A('Call the provider server-side','Read the secret only inside server execution.'),A('Return only the needed response data','Do not echo environment variables or internal headers back to the client.'),A('Inspect browser source and Network tools','Search for the secret or secret prefix. It should not appear.'),A('Add a server-side error response','A missing key or provider failure should produce a helpful UI message instead of a blank screen.')],[`AI replies work through the server route.`,`The raw API key is absent from page source and browser network responses.`,`Provider failures show a controlled error state.`],'Rotate the key immediately if it was ever committed to a public repository.',[T('The browser gets 500 from the AI route','Check the server logs and environment-variable name. Do not add the key to client code to “fix” it.'),T('The app sends duplicate requests','Disable Send during an active request and cancel/stop cleanly before allowing another.')]),
S('Add build-aware context controls','Project context should be deliberate, visible, and limited to what is useful.','35–50 min',V('terminal-context','Expandable context preview shows project title, current phase, materials, and selected troubleshooting details before send.'),[
A('Add a Current Project shortcut','Read the project and phase currently open in Pi Command Center.'),A('Add Explain simpler','Send the step text plus a request for simpler language.'),A('Add Troubleshoot this step','Include expected result and the specific symptom the user chooses.'),A('Add What should I check next','Include only current phase completion state and relevant checklist data.'),A('Show a context preview','Let the user see exactly what will be sent before the request leaves the browser.'),A('Exclude private notes by default','Do not automatically attach personal notes, credentials, or unrelated local data.'),A('Make context optional','The terminal should still support a normal blank conversation.')],[`One tap can prepare help for the exact build phase.`,`The user can inspect and remove context before sending.`,`Private notes are not silently attached.`]),
S('Add only allowlisted local Pi actions','AI assistance can request device status without becoming a remote shell.','45–75 min',V('terminal-agent','AI request → local allowlist → approved Pi action such as temperature/status → result. No arbitrary shell command.'),[
A('Create a tiny local agent','Run it on the Pi and expose only specific endpoints such as /status or /temperature.'),A('Define an allowlist','Each allowed action maps to code you wrote. Do not accept arbitrary command strings.'),A('Separate read and write actions','Status reads can be easier to approve than actions that modify hardware state.'),A('Require UI confirmation for write actions','Changing display mode, GPIO output, or shutdown should require a visible confirmation.'),A('Log approved actions','Store timestamp, requested action, and result without secrets.'),A('Reject everything else','Unknown action names should return a clear 403/unsupported response.'),A('Test with intentionally invalid actions','Confirm the agent refuses them.')],[`The AI can retrieve approved status only.`,`Unknown or arbitrary shell commands are rejected.`,`State-changing actions require user confirmation.`],'Never expose an unrestricted terminal, shell endpoint, or command-execution API to the public internet.')
]}));
projects.push(wrap({id:'cyberdeck',title:'Portable Cyberdeck',icon:'⌨️',difficulty:'Advanced',time:'10–14 hours',category:'Portable',scene:'cyberdeck',summary:'Build a portable Pi computer with the touchscreen, mini keyboard, reliable battery power, cooling, and a dedicated launcher.',goal:'A transportable Pi 5 system that survives movement, remains cool, powers reliably from USB-C PD, and is comfortable to type on.',materials:[required('Raspberry Pi 5','Main computer.'),required('7-inch touchscreen','Primary display.'),required('Rii mini keyboard','Compact input.'),required('USB-C PD power bank suitable for Pi 5','Portable power source.'),required('High-quality short USB-C cable','Reduces voltage drop.'),required('Rigid enclosure','Holds the system.'),required('Velcro or standoffs','Secures components.'),required('Ventilation openings','Allows heat to escape.'),optional('Handle or hinge','Improves portability depending on enclosure design.')],safety:['Do not use an underspecified phone battery pack just because it has USB-C.','Do not bury the Pi 5 heatsink in foam or a sealed compartment.','Power off before moving internal cables or mounts.'],phases:[
S('Prove the portable power source under load','The battery must work under sustained Pi 5 load before it becomes part of the enclosure.','30–45 min',V('powerbank','USB-C PD battery, short cable, Pi 5, display, and a 15-minute load test.'),[
A('Read the power bank output label','Confirm its USB-C PD capabilities and maximum output. Use a bank intended for sustained USB-C device power.'),A('Use a short high-quality USB-C cable','Long thin cables can introduce voltage drop even with a capable power bank.'),A('Boot the Pi and display from the bank','Start with no enclosure so heat and warning messages are easy to observe.'),A('Open several apps or run a CPU-heavy task','The goal is to create a more demanding condition than an idle desktop.'),A('Run at least 15 minutes','Watch for undervoltage icons, disconnects, screen flicker, or random restart.'),A('Check cable plugs for warmth or looseness','Stop if a connector becomes abnormally hot or unstable.'),A('Record the battery/cable combination that passed','Use the same known-good combination in the final build.')],[`The Pi remains powered and stable for 15 minutes under load.`,`No undervoltage warning appears.`,`The USB-C connection does not move easily or become abnormally hot.`],'Do not use the PiSugar Zero battery as the Pi 5 main portable power source.'),
S('Prototype the enclosure in cardboard','Ergonomics are easier to fix in cardboard than after drilling or gluing a rigid case.','45–60 min',V('cyberdeck-mockup','Cardboard mock enclosure with screen angle, keyboard position, battery, cable exits, and Pi clearance.'),[
A('Cut a base roughly matching the planned enclosure','Use the real screen and keyboard dimensions, not product-page guesses.'),A('Place the display first','Test upright, slightly tilted, or hinged positions at your normal viewing distance.'),A('Place the keyboard','Type several sentences with the deck on a desk and then on your lap.'),A('Add Pi and battery placeholders','Use the actual devices if safe, still powered off, to check thickness and cable reach.'),A('Mark every port you need','USB, microSD, USB-C power, Ethernet, and any service access should not be buried accidentally.'),A('Simulate lid or hinge movement','Move slowly and watch the intended cable paths for pinch points.'),A('Adjust until comfortable','Change the design now rather than accepting a poor typing angle.')],[`You can type comfortably.`,`Required ports remain reachable.`,`The planned cable paths survive the full hinge/lid movement.`]),
S('Design cooling before permanent mounting','Portable enclosures can trap Pi 5 heat much more than an open desk setup.','30–45 min',V('cyberdeck-airflow','Cool air enters below/side, passes the metal Pi case fins, and exits without the battery blocking flow.'),[
A('Choose the Pi case position','Place the heatsink fins in a path where air can move rather than facing a solid wall a few millimeters away.'),A('Mark intake and exhaust areas','Put openings on opposite sides or otherwise create a clear convection path.'),A('Separate the battery from the hottest zone','Do not press the battery against the Pi heatsink.'),A('Keep fabric and foam away from fins','Soft padding can insulate the hottest part of the enclosure.'),A('Build the ventilation into the mockup','Test with temporary openings before cutting the final enclosure.'),A('Run a 30-minute closed/mock test','Measure temperature while the system is positioned the same way you will actually use it.'),A('Increase ventilation if temperature climbs continually','Do not rely on a short boot test to judge final thermals.')],[`Temperature stabilizes during a 30-minute test.`,`Battery and cable surfaces stay clear of the Pi heatsink.`,`Air openings are not blocked in normal use.`]),
S('Mount screen, Pi, battery, and keyboard without stress','Every part should stay fixed while serviceable connectors remain accessible.','60–90 min',V('cyberdeck-mount','Rigid mounts support component frames; no screw or strap presses into LCD or exposed circuit traces.'),[
A('Power everything off','Disconnect the battery from the Pi before mounting.'),A('Mount the display by its rigid frame','Use brackets, standoffs, or removable fasteners on supported edges.'),A('Mount the Pi case','Keep ports and ventilation reachable. Leave room to remove the microSD if you want field serviceability.'),A('Secure the battery','Use a strap or Velcro on a rigid enclosure surface. Do not puncture or clamp the battery pack.'),A('Mount the keyboard reversibly','You may need to charge, replace, or pair it later.'),A('Route the DSI ribbon in a broad curve','Keep it away from hinge edges and screw points.'),A('Use short cables where practical','Reduce loops that can snag when the enclosure moves.'),A('Perform a powered-off shake test','Gently tilt and shake the case. Nothing should slide, rattle, or pull a connector.')],[`All major parts remain fixed during gentle handling.`,`No mount presses the LCD or battery casing.`,`Ports needed for normal use remain accessible.`]),
S('Finish cable management and build the launcher','The cyberdeck should behave like a dedicated appliance, not a pile of hardware inside a case.','60–90 min',V('cyberdeck-launcher','Large touch launcher tiles: Browser, AI, Dashboard, Notes, Files, GitHub, System, and Safe Shutdown.'),[
A('Add strain relief at the external power point','A tug on the cable should not transfer directly to the Pi USB-C socket.'),A('Cycle every hinge/lid movement slowly','Watch every cable through the entire travel.'),A('Label or color-code service cables','Make it obvious which cable is display, battery power, and keyboard receiver.'),A('Build large launcher tiles','Use Browser, AI, Dashboard, Notes, Files, GitHub, and System.'),A('Add a safe Shutdown action','Require confirmation, then run a controlled shutdown rather than cutting battery power.'),A('Support touch and keyboard navigation','Every launcher destination should work with both.'),A('Test offline behavior','Local tools and the launcher shell should fail gracefully when Wi-Fi is unavailable.')],[`The deck can be opened/closed without cable pinch.`,`Launcher actions work by touch and keyboard.`,`Shutdown provides a clear confirmation and clean OS halt.`],'Whenever possible, shut Raspberry Pi OS down cleanly before removing battery power.')
]}));
projects.push(wrap({id:'home-panel',title:'Home Assistant Panel',icon:'🏠',difficulty:'Medium',time:'4–6 hours',category:'Smart Home',scene:'home',summary:'Use the Pi touchscreen as a dedicated smart-home control panel with large room controls, scenes, safe credential handling, and kiosk mode.',goal:'A simple wall/desk panel that shows real device state, provides deliberate controls, and protects higher-risk lock/alarm/garage actions.',materials:[required('Raspberry Pi display setup','Provides the dedicated touch panel.'),required('Home Assistant instance','Provides device state and control.'),required('Home network','Connects the panel to Home Assistant.'),optional('Smart bulbs or plugs','Useful first devices for testing.'),optional('Wall mount','Only after the panel is stable on a desk.')],safety:['Treat locks, alarms, doors, and garages as higher-risk than lights.','Do not expose a long-lived Home Assistant token in public client code.'],phases:[
S('Inventory only the devices and scenes you actually use','A useful panel is a short list of frequent actions, not every entity in Home Assistant.','25–35 min',V('home-map','Rooms map with a small set of priority controls and scenes.'),[
A('List each room','Start with rooms you interact with daily.'),A('List each controllable device','Use friendly names and note current Home Assistant entity names separately.'),A('Mark frequent actions','Example: bedroom lights off, living room lamp on, fan toggle.'),A('Choose three to five scenes','Morning, Focus, Evening, Sleep, and Away only if they match real routines.'),A('Mark sensitive actions','Locks, alarms, garages, and security-related controls need extra confirmation.'),A('Remove low-value entities from the first screen','Sensors can live in details pages rather than crowding the primary controls.')],[`Every first-screen control has a real daily purpose.`,`Sensitive actions are identified before UI work begins.`]),
S('Design a wall/desk touch layout','A person standing at the panel should understand the state in one glance.','35–50 min',V('home-ui','Large room cards, obvious On/Off states, wide sliders, and separate scene controls.'),[
A('Use one large card per priority room','Give the room name and one or two common controls.'),A('Make On and Off visually distinct','Do not rely on tiny switch position alone.'),A('Use wide sliders','Brightness and thermostat controls need enough width for a finger.'),A('Separate scenes from individual devices','A scene can change multiple devices and should look different from a simple toggle.'),A('Move sensitive actions away from common lighting','Avoid placing Unlock directly beside a light switch.'),A('Add clear offline state','A device that cannot be reached should look unavailable instead of falsely On or Off.')],[`Common controls are one or two taps away.`,`State is visible from normal viewing distance.`,`Sensitive actions are not easy to hit accidentally.`]),
S('Connect Home Assistant without exposing credentials','Read state first, then add write controls after the data path is proven.','45–75 min',V('home-secure','Pi browser → server route → Home Assistant API. Token stays server-side.'),[
A('Confirm Home Assistant is reachable from the Pi','Open the normal Home Assistant UI on the Pi first.'),A('Choose the minimum integration/token method','Use the least privilege practical for the panel.'),A('Store secrets server-side','Use environment variables or a local protected service, not public browser code.'),A('Fetch one device state','Start with a harmless light or plug.'),A('Render loading, success, and offline states','The card should never become blank.'),A('Add a write action for the same safe device','Send a controlled command through your server/local layer.'),A('Re-read the state after the command','The UI should reflect the actual Home Assistant result, not just assume success.')],[`At least one device shows accurate live state.`,`A safe test device can be controlled.`,`No long-lived token appears in browser source.`],'Do not make lock/alarm/garage controls the first write test.'),
S('Add scenes, confirmation rules, and duplicate-tap protection','Smart-home commands need clear feedback because network actions are not instantaneous.','35–50 min',V('home-scenes','Scene button → confirmation for sensitive scene → processing state → success/failure feedback.'),[
A('Add only real scenes','Map buttons to existing Home Assistant scenes or scripts you actually use.'),A('Show a processing state','Disable repeated taps while a command is in flight.'),A('Show success or failure feedback','Keep it brief but visible.'),A('Require confirmation for Away and security-sensitive actions','Use clear wording that states what will happen.'),A('Do not confirm ordinary light toggles unless needed','Too many confirmations make the panel frustrating and encourage blind tapping.'),A('Test network loss during a command','The UI should recover and allow a retry without sending repeated unknown actions.')],[`Scenes show processing and success/failure state.`,`Sensitive actions cannot run from one accidental tap.`,`Repeated rapid taps do not create duplicate commands.`]),
S('Run the panel in kiosk mode and only then consider wall mounting','Desk testing should prove the software before the panel becomes physically harder to reach.','45–60 min',V('home-kiosk','Pi cold-boots into the Home panel with a protected maintenance exit and night/dim mode.'),[
A('Open the production Home panel route','Test every room and scene on the Pi display.'),A('Test finger reach at the planned mounting height','Controls comfortable on a desk can be awkward on a wall.'),A('Add night/dim behavior','Reduce brightness and unnecessary content after dark.'),A('Test manual Chromium kiosk mode','Verify escape/maintenance behavior.'),A('Configure one autostart method','Avoid duplicate browser launches.'),A('Reboot twice','The panel should return automatically.'),A('Mount only after repeated stable use','Use a desk stand for a few days first if possible.')],[`The Pi cold-boots into the panel.`,`Night mode is comfortable.`,`You know how to exit kiosk mode for maintenance.`])
]}));
projects.push(wrap({id:'electronics-lab',title:'Electronics Lab',icon:'💡',difficulty:'Medium',time:'5–7 hours',category:'GPIO',scene:'breadboard',summary:'Learn safe GPIO basics with LEDs and buttons, then expose hardware status to the dashboard.',goal:'A correctly wired LED + resistor + push button circuit controlled with gpiozero, with safe 3.3 V GPIO practices and a simple local status endpoint.',materials:[required('Raspberry Pi 5','Provides GPIO.'),required('Breadboard','Builds circuits without soldering.'),required('Jumper wires','Connects Pi header to breadboard.'),required('LEDs','Visible output devices.'),required('220–330 Ω resistors','Limits LED current.'),required('Push buttons','Provides physical input.'),required('gpiozero Python package','Simplifies GPIO control.')],safety:['Raspberry Pi GPIO uses 3.3 V logic. Do not feed 5 V into a GPIO input.','Always use a current-limiting resistor with an LED.','Power off before moving breadboard wires during beginner wiring.'],phases:[
S('Learn BCM numbering and identify safe pins','Physical header pin numbers and BCM GPIO numbers are not the same thing.','20–30 min',V('gpio-map','40-pin header highlighting 3.3 V, GND, and BCM GPIO17.'),[
A('Open a Raspberry Pi 5 GPIO pinout reference','Keep it visible beside the breadboard.'),A('Choose BCM numbering for this course','Python examples will refer to GPIO numbers such as GPIO17.'),A('Find at least two GND pins','Knowing alternatives helps with breadboard routing.'),A('Locate GPIO17','Point to the physical header position while reading the BCM label.'),A('Locate 3.3 V and 5 V pins','Learn the difference so you do not accidentally connect 5 V to a GPIO input.'),A('Keep power disconnected','Do not begin the circuit while the Pi is powered.')],[`You can identify GPIO17 and GND without guessing.`,`You can distinguish the 3.3 V and 5 V header pins.`],'Applying 5 V directly to a GPIO input can damage the Pi.'),
S('Build the first LED circuit with a resistor','The resistor protects the LED and GPIO from excessive current.','25–40 min',V('breadboard-led','GPIO17 → 220–330 Ω resistor → LED anode; LED cathode → GND.'),[
A('Place the LED across separate breadboard rows','Do not put both legs in one connected row.'),A('Identify LED polarity','Longer leg is usually anode; shorter leg and flat body edge usually mark cathode.'),A('Insert a 220–330 Ω resistor','Use the resistor in series between GPIO17 and the LED.'),A('Connect GPIO17 to the resistor','Trace the exact breadboard row from the Pi jumper to one resistor leg.'),A('Connect resistor to LED anode','Verify the second resistor leg shares the intended row with the LED anode.'),A('Connect LED cathode to GND','Use a known Pi GND header pin.'),A('Trace the circuit with your finger','GPIO17 → resistor → LED → GND. Confirm there is no direct GPIO-to-GND jumper.'),A('Take a close-up photo before powering','This becomes your known wiring reference.')],[`The circuit path includes exactly one current-limiting resistor.`,`No GPIO pin is directly shorted to GND.`,`LED polarity is known.`],'Never connect the LED directly from GPIO17 to GND without the resistor.'),
S('Blink the LED with gpiozero','This proves both the circuit and Python GPIO control.','20–30 min',V('breadboard-blink','Python script toggles GPIO17; LED alternates on/off once per second.'),[
A('Power on only after the wiring check','Do not move jumpers once powered for this beginner test.'),A('Install gpiozero if needed','Use the package command below.'),A('Create a Python file','Import LED from gpiozero and sleep from time.'),A('Create LED(17)','The 17 refers to BCM GPIO17.'),A('Turn on, wait, turn off, wait','Repeat in a loop so the result is obvious.'),A('Run the script','Watch the LED rather than changing wires immediately if it does not light.'),A('If it fails, stop the script and power off','Then verify polarity, row alignment, resistor value, and pin number.')],[`The LED repeatedly turns on and off.`,`The Pi remains stable and no component becomes hot.`],'Power down before rewiring a failed circuit.',[T('LED never lights','Check LED polarity first, then breadboard row alignment, GPIO number, and resistor connection.'),T('LED stays on constantly','Check the script is controlling the correct BCM pin and that the LED is not accidentally connected to 3.3 V instead of GPIO17.')],[C('Install gpiozero','sudo apt install -y python3-gpiozero','gpiozero installs or reports that it is already current.'),C('Example blink script',"python3 - <<'PY'\nfrom gpiozero import LED\nfrom time import sleep\nled=LED(17)\nfor _ in range(10):\n    led.on(); sleep(1)\n    led.off(); sleep(1)\nPY",'The LED blinks ten times.')]),
S('Add a push button input safely','A four-leg tactile button has internally connected leg pairs, so orientation matters.','25–40 min',V('breadboard-button','Button bridges the breadboard center gap; one side goes to GPIO input and the other to GND using internal pull-up.'),[
A('Shut down and disconnect power','Do not add the button to a powered beginner circuit.'),A('Place the button across the center gap','This prevents both internally connected sides from landing on the same breadboard strip.'),A('Choose an input GPIO','Use a safe general-purpose input such as GPIO27 for this guide.'),A('Connect one side to GPIO27','Use a jumper from the chosen button row to the correct header pin.'),A('Connect the opposite side to GND','Do not connect the button to 5 V.'),A('Use gpiozero Button with pull-up behavior','The input reads active when pressed to GND.'),A('Power on and print press events','Press repeatedly and confirm one logical event per press.'),A('Add debounce if needed','If a single physical press appears multiple times, use software bounce handling.')],[`Each physical press produces the intended input event.`,`The button circuit uses GPIO + GND, not 5 V.`]),
S('Make the button control the LED and expose status locally','Combine input and output, then bridge status to the web without exposing a shell.','45–60 min',V('gpio-agent','Button event controls LED locally; tiny local /status endpoint reports LED and last-button state to dashboard.'),[
A('Keep the known-good LED circuit','Do not rewire the LED while adding software behavior.'),A('Keep the tested button input','Use the same known-good GPIO and GND path.'),A('Write a script that toggles or holds the LED','Choose one simple interaction and confirm it locally first.'),A('Add explicit state variables','Track LED state and last button time.'),A('Create a tiny local status endpoint','Return only structured status such as LED on/off and last press.'),A('Do not accept arbitrary shell commands','The endpoint should have fixed behavior you wrote.'),A('Display status in Pi Command Center','Poll modestly or use a local push method.'),A('Test web disconnection','The local button/LED behavior should remain safe if the web UI disappears.')],[`Button presses reliably change the LED.`,`Dashboard can read status.`,`No general shell or arbitrary command endpoint exists.`],'Keep electrical GPIO control local to the Pi. A cloud-hosted Vercel page cannot directly drive the header pins.')
]}));
projects.push(wrap({id:'pomodoro',title:'Pomodoro Station',icon:'⏱️',difficulty:'Easy',time:'3–5 hours',category:'Productivity',scene:'timer',summary:'Create a dedicated focus timer, then optionally add physical buttons and status LEDs.',goal:'A reliable 25-minute focus station with saved sessions, break mode, optional GPIO controls, and clear idle/focus/break states.',materials:[required('Raspberry Pi 5','Runs the station.'),required('7-inch touchscreen','Primary timer interface.'),required('Vercel app','Hosts the timer UI.'),optional('Push buttons','Adds physical Start/Pause and Complete controls.'),optional('LEDs and resistors','Adds focus/break status lights.')],safety:['Complete the Electronics Lab button/LED exercise before adding optional GPIO hardware.','Every LED requires a current-limiting resistor.'],phases:[
S('Build the complete touch timer before adding hardware','Software behavior should be stable before GPIO is introduced.','40–60 min',V('timer-ui','Large 25:00 display, current task, Start, Pause, Reset, and Complete controls.'),[
A('Place a large 25:00 countdown at the center','It should be readable from normal desk distance.'),A('Add a single current-task field','Keep task entry short and visible.'),A('Add Start, Pause, Reset, and Complete','Use large buttons with text labels.'),A('Disable invalid actions','Start should not start a second timer; Pause should be disabled when idle.'),A('Use a reliable clock source','Compute remaining time from timestamps so tab delays do not permanently drift the countdown.'),A('Add a clear completion state','Show a visual alert and optional subtle sound.'),A('Test a shortened 30-second development session','Verify all state transitions before waiting through a full 25 minutes.')],[`Start, Pause, Resume, Complete, and Reset all work.`,`The countdown does not create duplicate timers.`,`Completion is obvious but not disruptive.`]),
S('Save completed sessions locally','Persistence makes the station useful without requiring a database.','30–45 min',V('timer-history','Completed session record stores task, start/end time, duration, and daily totals in localStorage.'),[
A('Define the session record','Save task, start timestamp, end timestamp, and focused minutes.'),A('Write only when a session completes','Do not count resets or abandoned sessions as completed.'),A('Store records in localStorage','Use a versioned key so future schema changes are manageable.'),A('Show today’s completed count','Filter by local date.'),A('Show today’s focused minutes','Sum completed durations for the day.'),A('Add a clear-history action','Require a confirmation before deleting records.'),A('Refresh the page','Confirm history remains and the app starts in a sensible idle state.')],[`Completed sessions survive refresh.`,`Daily count and minutes match the stored sessions.`,`Clear History requires confirmation.`]),
S('Add break mode and explicit transitions','Focus and break should look and behave differently enough to avoid confusion.','25–40 min',V('timer-break','Focus complete → offer 5-minute Break; distinct break screen with Skip Break and Start Next Focus.'),[
A('Offer a 5-minute break after completion','Do not force-start it.'),A('Change the visual state','Use different wording and a clear Break label.'),A('Add Skip Break','Return to idle without counting a focus session twice.'),A('Add Start Next Focus','Create a fresh 25-minute interval deliberately.'),A('Do not automatically begin another focus interval','A new work session should always require a deliberate action.'),A('Test refresh during break','Restore or safely reset the state according to your design.')],[`Focus and break are visually distinct.`,`No new focus session starts without an explicit action.`]),
S('Add optional physical buttons only after the software timer passes','GPIO controls should call the same state functions as the touchscreen, not create a second timer implementation.','35–60 min',V('timer-buttons','Two labeled buttons: Start/Pause and Complete, wired using the known Electronics Lab button pattern.'),[
A('Complete the Electronics Lab button phase first','Use that known-good wiring pattern and power-off discipline.'),A('Power down before wiring','Add one Start/Pause button and one Complete button.'),A('Label the physical buttons','A portable or desk build becomes confusing quickly without labels.'),A('Handle presses in a local Pi process','Convert each press to one approved timer event.'),A('Reuse the same app state actions','Physical and touch controls should change the identical timer state.'),A('Add debounce','One press should produce one state change.'),A('Test long presses and repeated taps','They should not create duplicate completions.')],[`Physical buttons match touchscreen behavior.`,`One press produces one state change.`]),
S('Add optional focus/break LEDs','A small status light lets you read timer state without looking at the screen.','25–40 min',V('timer-led','Resistor-protected LEDs indicate Focus and Break; both off when idle.'),[
A('Choose one LED for Focus and one for Break','Document the color meaning.'),A('Use a 220–330 Ω resistor with each LED','Follow the Electronics Lab LED circuit.'),A('Drive the LEDs from the local Pi process','Map app state to approved GPIO outputs.'),A('Turn both off when idle','Do not leave ambiguous mixed states.'),A('Add an LED-disable option','Useful at night or when the station is in a bedroom.'),A('Power down before changing any LED wiring','Do not troubleshoot by moving powered jumpers.')],[`Focus state lights only the Focus LED.`,`Break state lights only the Break LED.`,`Idle turns both off.`])
]}));
projects.push(wrap({id:'glance',title:'Desk Info Center',icon:'ℹ️',difficulty:'Easy',time:'3–5 hours',category:'Display',scene:'glance',summary:'Create an always-on passive display that rotates through useful information with day/night behavior and kiosk mode.',goal:'A calm rotating display that communicates each screen in seconds, pauses on interaction, dims at night, and cold-boots into kiosk mode.',materials:[required('Raspberry Pi 5','Runs the display.'),required('7-inch display','Shows passive information.'),required('Chromium kiosk mode','Provides appliance-like display.'),required('Dashboard web app','Provides the Glance screens.')],safety:['Avoid maximum brightness in a dark room for long periods.','Keep a maintenance method to exit kiosk mode.'],phases:[
S('Choose five glance pages and define one job for each','A passive display becomes noise if every screen tries to show everything.','25–35 min',V('glance-pages','Five cards: Clock, Weather, Calendar, Fitness, Current Project.'),[
A('Choose no more than five initial pages','Start with Clock, Weather, Calendar, Fitness, and Current Project or equivalent.'),A('Write the one question each page answers','Example: Calendar answers “What is next?” not “Show my full schedule.”'),A('Use large text','Stand at your normal desk distance and verify headings and key values are readable.'),A('Remove unnecessary controls','Passive screens should not look like settings forms.'),A('Define data refresh frequency separately from page rotation','Weather may refresh every several minutes while pages rotate every 20–30 seconds.'),A('Create a fallback for missing data','Show a compact unavailable state without stopping rotation.')],[`Each page has one obvious purpose.`,`Main information is readable in under two seconds.`]),
S('Build calm automatic rotation with pause-on-touch','The display should feel ambient, not like a slideshow advertisement.','30–45 min',V('glance-rotate','Page A visible for 25 seconds → subtle fade → Page B; touch pauses the timer.'),[
A('Start with a 25-second dwell time','Make it configurable later.'),A('Advance one page at a time','Wrap from the last page back to the first.'),A('Use a short subtle fade','Avoid large zooms or sliding panels.'),A('Pause rotation on touch or click','Interaction means the user is reading or drilling in.'),A('Restart rotation after inactivity','Use a clear inactivity interval such as 60 seconds.'),A('Prevent multiple overlapping timers','Keep one rotation scheduler and cancel it before starting another.'),A('Test for several complete cycles','Watch for skipped pages or increasing speed caused by duplicate intervals.')],[`Every page appears once per cycle.`,`Touch pauses rotation.`,`Rotation resumes once after inactivity.`]),
S('Add day/night behavior','The same white clock that looks good at noon can be harsh at midnight.','25–40 min',V('glance-night','Day mode uses normal brightness; Night mode lowers brightness and reduces bright content.'),[
A('Define a Night mode schedule or manual switch','Use local time or a Settings toggle.'),A('Reduce software brightness and bright areas','Use darker backgrounds and less pure white surface area.'),A('Reduce content density at night','A clock and next alarm/event may be enough.'),A('Add a Wake control','A deliberate touch can temporarily restore normal view.'),A('Test in the actual dark room','Software screenshots on a bright laptop are not enough.'),A('Adjust the physical display brightness if needed','Do not rely only on CSS opacity if the backlight itself is too bright.')],[`Night mode is comfortable in the actual room.`,`Day mode remains readable in normal ambient light.`]),
S('Run Glance in kiosk mode and tune it from a full day of use','Real usage reveals which pages are useful and which are clutter.','45–60 min plus observation',V('glance-kiosk','Pi cold-boots into rotating Glance screen; after a day, unused pages are removed or slowed.'),[
A('Open the Glance route in Pi Chromium','Verify one full rotation cycle by touch.'),A('Test manual kiosk mode','Confirm there is no browser chrome in normal use.'),A('Configure one autostart launch','Reboot and verify rotation begins automatically.'),A('Leave it on your desk for a day','Notice which screens you actually look at.'),A('Remove ignored pages','Fewer useful pages are better than a large rotation.'),A('Increase dwell time for useful pages','Tune based on how long you naturally read them.'),A('Check CPU usage and temperature','A passive display should not consume excessive resources just to animate.')],[`Cold boot returns to Glance automatically.`,`Rotation remains calm over long use.`,`The final page set contains information you actually use.`])
]}));
projects.push(wrap({id:'photo-frame',title:'Digital Photo Frame',icon:'🖼️',difficulty:'Easy',time:'3–5 hours',category:'Display',scene:'photo',summary:'Turn the Pi display into a rotating personal photo frame with secure collections, captions, preload, night schedule, and kiosk startup.',goal:'A smooth photo slideshow that preserves aspect ratio, protects private images, resumes the chosen collection, and avoids blank flashes between photos.',materials:[required('Raspberry Pi 5','Runs the frame.'),required('7-inch display','Shows images.'),required('Photo files or private Supabase Storage','Provides the photo library.'),required('Vercel app','Runs the slideshow interface.')],safety:['Private photos should not live in a public storage bucket.','Consider screen longevity and power use if running continuously.'],phases:[
S('Prepare a small 10–20 photo test album','A small controlled set makes orientation, crop, and loading problems obvious.','30–45 min',V('photo-album','Test collection contains landscape and portrait photos plus optional caption/date/location metadata.'),[
A('Choose 10–20 representative photos','Include both landscape and portrait images.'),A('Rotate files correctly before upload','Do not rely on every browser to interpret inconsistent orientation metadata identically.'),A('Create display-sized derivatives if originals are huge','The 7-inch screen does not benefit from loading enormous camera files for every slide.'),A('Keep originals elsewhere','The frame library should not be the only copy of important photos.'),A('Add optional captions and dates','Keep them short enough to remain secondary to the image.'),A('Use private storage for private images','Require authenticated or signed access rather than a public bucket.'),A('Load the album on the Pi','Confirm all files display and none are unexpectedly rotated.')],[`All test photos load.`,`Portrait and landscape orientation is correct.`,`Private images are not publicly enumerable.`]),
S('Build the full-screen image viewer without distortion','The photo, not navigation, should dominate the screen.','35–50 min',V('photo-viewer','Full-screen image on black background with subtle caption and large invisible/edge Prev/Next touch zones.'),[
A('Use the available screen area','Remove unnecessary header chrome in Photo mode.'),A('Preserve aspect ratio','Use contain for full-image visibility or cover only if deliberate cropping is acceptable.'),A('Use black around letterboxed images','It minimizes distraction and looks clean on the Pi display.'),A('Keep captions subtle','Allow them to be hidden.'),A('Add large Previous and Next touch zones','Avoid tiny arrow icons as the only navigation target.'),A('Add a Settings exit','There must be a clear way to choose collection or leave Photo mode.'),A('Test portrait and landscape back-to-back','Verify layout does not jump or stretch.')],[`No photo is stretched.`,`Portrait and landscape both look intentional.`,`Prev/Next works reliably by touch.`]),
S('Add smooth automatic advance with preloading','Preloading prevents the blank flash that makes a digital frame feel cheap.','30–45 min',V('photo-preload','Current image visible while next image loads invisibly; gentle fade occurs only after preload success.'),[
A('Start with a 15-second interval','Make the value configurable later.'),A('Preload the next image','Create or fetch it before changing the visible slide.'),A('Advance only after preload succeeds','If loading fails, keep the current image and move to the next valid candidate.'),A('Use a short fade','Avoid long GPU-heavy transitions.'),A('Pause on user touch','Manual browsing should not fight the auto-advance timer.'),A('Resume after inactivity','Restart one timer only.'),A('Test on slower Wi-Fi','Look for blank screens, rapidly skipped images, or duplicate timers.')],[`No blank flash occurs during normal advance.`,`A failed image does not break the slideshow.`,`Manual navigation pauses auto-advance.`]),
S('Organize collections and persist the chosen album','Collections make the frame useful without putting controls over every image.','25–40 min',V('photo-collections','Settings lists Family, Travel, Friends, Favorites, Projects, plus Shuffle and remembered selection.'),[
A('Create a few meaningful collections','Use names you will actually choose.'),A('Keep collection selection in Settings','Do not overlay album management on the photo itself.'),A('Remember the selection locally','The frame should resume the same collection after refresh/reboot.'),A('Add Shuffle as an option','Shuffle order without losing the collection boundary.'),A('Handle an empty collection','Show a friendly message and Settings link instead of a blank screen.'),A('Do not expose storage secrets','Browser access should use safe public assets or short-lived/signed access as appropriate.')],[`The chosen collection survives refresh.`,`Empty collections show a recoverable state.`,`Shuffle does not mix in photos from another collection unexpectedly.`]),
S('Add night schedule and kiosk startup','A dedicated frame should behave predictably when nobody is touching it.','35–50 min',V('photo-kiosk','Kiosk slideshow starts after boot; Night schedule dims or blanks the display and resumes later.'),[
A('Open the Photo route on the Pi','Run through manual and automatic navigation.'),A('Define a Night schedule','Choose dim, black screen, or display-off behavior appropriate to your room.'),A('Provide a manual Wake action','Touch or another deliberate interaction can restore the frame.'),A('Test manual kiosk mode','Confirm browser chrome is hidden.'),A('Add one autostart method','Reboot and confirm the selected collection resumes.'),A('Observe power and heat after extended use','A photo frame may run for many hours.'),A('Adjust brightness for screen longevity and comfort','Maximum brightness is rarely necessary indoors.')],[`Cold boot resumes the intended slideshow.`,`Night behavior occurs at the intended time.`,`The selected collection is preserved.`])
]}));
projects.push(wrap({id:'magic-frame',title:'Magic Mirror Frame',icon:'✨',difficulty:'Advanced',time:'7–10 hours',category:'Hybrid',scene:'magic',summary:'Combine the stable Smart Mirror and Photo Frame so the hidden display wakes only when needed and can reveal photos or dashboard information.',goal:'A hybrid mirror that looks dormant when black, wakes from a deliberate trigger, times out safely, reveals photos cleanly, and never exposes desktop clutter.',materials:[required('Completed Smart Mirror hardware','Provides the tested reflective enclosure.'),required('Completed Photo Frame mode','Provides stable image display.'),required('Pi local agent','Handles approved local triggers and display actions.'),optional('Push button','Simple physical wake trigger.'),optional('Motion sensor','Advanced wake trigger only after voltage/interface verification.')],safety:['Complete Smart Mirror thermal/stability testing first.','Verify any motion sensor voltage and interface before wiring it to GPIO.','Do not troubleshoot unfinished mirror hardware and new trigger hardware at the same time.'],phases:[
S('Prove both prerequisite modes separately','Hybrid behavior should combine two known-good systems rather than hide unresolved faults.','30–45 min',V('magic-prereq','Smart Mirror passes stability test; Photo Frame mode runs smoothly before hybrid logic is enabled.','/assets/smart-mirror-finished-reference.jpg'),[
A('Run the Smart Mirror for at least 30 minutes','Verify display, heat, DSI stability, and kiosk startup.'),A('Test black-screen invisibility','Unused pixels should disappear convincingly behind the mirror in the real room.'),A('Run Photo Frame mode separately','Confirm smooth preload/advance and the intended collection.'),A('Reboot into each mode','Know that both work before combining them.'),A('Document the working settings','Brightness, mirror page URL/mode, photo collection, and timeout values should be known.'),A('Do not add a wake sensor yet','First combine the software modes using touch or keyboard.')],[`Smart Mirror is stable.`,`Photo Frame is stable.`,`Each mode works independently after reboot.`]),
S('Create a true dormant mirror state','The resting state must contain no accidental bright UI that reveals the hidden display.','25–40 min',V('magic-sleep','Pure black full-screen sleep page behind mirror; no cursor, toast, status bar, or bright browser chrome.'),[
A('Create a dedicated Sleep mode','Render pure black across the entire application viewport.'),A('Hide all normal navigation','No white header, loading spinner, or persistent status chip should remain.'),A('Hide or move the cursor','A bright mouse cursor can spoil the illusion.'),A('Reduce display brightness if needed','Balance wake readability with dormant glow.'),A('Check from several room angles','The black state should look like a normal mirror in the actual installation.'),A('Test a network error while sleeping','An offline banner should not suddenly light the mirror. Queue the error for the next wake instead.')],[`Dormant state looks like a normal mirror.`,`No bright UI appears while sleeping.`]),
S('Add a deliberate wake trigger before adding motion sensing','Touch or a physical button is easier to debug than a sensor and reduces false wakes.','35–50 min',V('magic-wake','Sleep → touch/button trigger → Dashboard or Photo choice. Local agent only accepts approved wake action.'),[
A('Start with touch or keyboard','Map one explicit interaction to wake the UI.'),A('Choose the wake destination','Either show a small choice screen or go directly to Dashboard.'),A('If adding a button, reuse the Electronics Lab pattern','Power down before wiring and use a safe GPIO + GND input.'),A('Handle the trigger locally','Use an allowlisted local event, not an arbitrary shell endpoint.'),A('Debounce physical triggers','One press should produce one wake.'),A('Add a manual Sleep action','The user should be able to return to the black state immediately.'),A('Test 20 wake/sleep cycles','Look for missed events, duplicate wake, or browser focus problems.')],[`One deliberate trigger wakes every time.`,`One action returns to Sleep.`,`Repeated cycles do not create duplicate timers or windows.`]),
S('Add an inactivity timeout with interaction reset','The frame should return to a mirror automatically but never disappear while you are actively using it.','30–45 min',V('magic-timeout','Wake starts a 60-second timer; touch resets timer; inactivity returns to black; Keep Awake can suspend timeout.'),[
A('Start with a 60-second timeout','Use a value long enough to read the dashboard.'),A('Reset the timer on meaningful interaction','Touch, navigation, or manual photo advance can count as activity.'),A('Return to Sleep cleanly','Clear overlays and focus states before switching to black.'),A('Add Keep Awake','Allow deliberate longer use without fighting the timeout.'),A('Cancel stale timers','Only one timeout should be active. Clear it whenever mode changes.'),A('Test at the timeout boundary','Interact just before expiration and confirm it resets correctly.'),A('Test network failure during wake','Timeout should still return to black even if a fetch is stuck.')],[`The display sleeps after inactivity.`,`Active use resets the timer.`,`Keep Awake prevents unwanted sleep.`]),
S('Add Photo Reveal mode and only then optional motion sensing','The photo should appear and disappear without exposing the desktop or unrelated app chrome.','45–75 min',V('magic-photo','Black mirror → gentle photo reveal → optional navigation → timeout → black mirror.'),[
A('Add a Photo action from the wake screen','Use the already-stable Photo Frame viewer.'),A('Fade from black only after the image is preloaded','Do not reveal a white loading screen.'),A('Keep dark margins around non-full-screen photos','This preserves more of the mirror appearance.'),A('Reset the inactivity timer on photo navigation','Manual browsing counts as interaction.'),A('Return directly to black on timeout','Do not flash the dashboard or browser chrome between modes.'),A('If adding motion, verify the exact sensor voltage first','Read the sensor documentation and confirm whether its output is safe for 3.3 V GPIO.'),A('Add a cooldown for motion wakes','Prevent continuous motion from keeping the display permanently awake unless that is intentional.'),A('Keep touch/button as a fallback','You need a simple maintenance trigger if the sensor fails.')],[`Photo reveal starts without a bright loading flash.`,`Timeout returns directly to black.`,`Optional sensor output is verified safe before wiring.`],'Never connect an unknown sensor output to the Pi GPIO based only on wire color or a generic diagram.')
]}));
window.PI_COURSES_V2=projects;
window.PI_COURSES_V2_VERSION='2.0.0';
})();