const fs=require('fs'),vm=require('vm');
const required=['index.html','course-v2.css','course-v4.css','course-v2-data.js','course-v2-fixes.js','course-v4-enhancements.js','course-v9-prerequisite.js','course-v2.js','sw.js','assets/reference/pi5-board.svg','assets/reference/dsi-ribbon.svg','assets/reference/imager-flow.svg'];
for(const f of required)if(!fs.existsSync(f))throw new Error(`Missing ${f}`);
for(const f of ['course-v2.js','course-v2-fixes.js','course-v4-enhancements.js','course-v9-prerequisite.js'])new vm.Script(fs.readFileSync(f,'utf8'),{filename:f});
const context={window:{},console,document:{},requestAnimationFrame:()=>{},MutationObserver:function(){this.observe=()=>{}}};vm.createContext(context);
new vm.Script(fs.readFileSync('course-v2-data.js','utf8')).runInContext(context);
if(!Array.isArray(context.window.PI_COURSES_V2)||context.window.PI_COURSES_V2.length!==10)throw new Error('Expected 10 base project courses');
new vm.Script(fs.readFileSync('course-v9-prerequisite.js','utf8')).runInContext(context);
const courses=context.window.PI_COURSES_V2;
if(courses.length!==11)throw new Error(`Expected 11 total courses including prerequisite, got ${courses.length}`);
const setup=courses[0];if(!setup||setup.id!=='pi-setup')throw new Error('START HERE prerequisite must be first');
if(setup.phases.length<8)throw new Error('Prerequisite must contain at least 8 guided phases');
for(const token of ['Raspberry Pi Imager','Raspberry Pi OS','Wi-Fi','SSH','Terminal','git --version','python3 --version','sudo apt full-upgrade','cold boot'])if(!JSON.stringify(setup).toLowerCase().includes(token.toLowerCase()))throw new Error(`Prerequisite missing ${token}`);
const html=fs.readFileSync('index.html','utf8');for(const token of ['START HERE: Raspberry Pi 5 Setup','course-v9-prerequisite.js?v=9.0.0','course-v4.css?v=9.0.0','sw.js?v=9.0.0'])if(!html.includes(token))throw new Error(`Root shell missing ${token}`);
const fixes=fs.readFileSync('course-v2-fixes.js','utf8');for(const bad of ['boot-screen.jpg','dsi-align.jpg','dsi-seated.jpg','photo-sprite-v3.jpg'])if(fixes.includes(bad))throw new Error(`Legacy bitmap referenced by active visual layer: ${bad}`);
const sw=fs.readFileSync('sw.js','utf8');if(!sw.includes("pi-command-course-v9"))throw new Error('Service worker cache not V9');if(!sw.includes("course-v9-prerequisite.js?v=9.0.0"))throw new Error('Prerequisite not cached');if(!sw.includes("cache:'no-store'"))throw new Error('Fresh asset policy missing');
console.log(`COURSE_VALIDATION_OK courses=${courses.length} prerequisitePhases=${setup.phases.length} setupFirst=yes cache=v9 legacyBitmaps=blocked`);